export type NoteListItem = {
  id: string;
  url: string;
  author: string;
  title: string;
  publishedAt?: string;
  sourceType: string;
  pipeline: string;
  level: string;
  productScope: string;
  status: string;
  lastFetchedAt?: string;
  commentTotal: number;
  positiveCount: number;
  negativeCount: number;
  questionCount: number;
  brandMentionTop5: number;
  addedAt: string;
  coverUrl?: string;
  category1?: string;
  category2?: string;
  noteType?: string;
  readCount?: number;
  interactionCount?: number;
  likeCount?: number;
  favoriteCount?: number;
  creatorLevel?: string;
  brand?: string;
  notePrice?: number;
  latestSnapshotTime?: string;
  latestL1Count?: number;
  latestL2Count?: number;
  latestSnapshotTotal?: number;
  prevSnapshotTotal?: number;
  commentDelta: number;
  isFetched: number;
  isProfileComplete: number;
  pendingRiskCount: number;
};

export type NotesListResponse = {
  ok: boolean;
  items: NoteListItem[];
  total: number;
  page: number;
  pageSize: number;
  summary: {
    total: number;
    ownedCount: number;
    scanCount: number;
    completeCount: number;
    missingProfileCount: number;
    reportableCount: number;
    baseCount: number;
    supplementCount: number;
    fetchedCount: number;
    unfetchedCount: number;
    totalComments: number;
    totalReads: number;
    totalInteractions: number;
  };
};
