export const sectionLabels: Record<string, [string, string]> = {
  'CONTENT STRATEGY': ['内容策略', 'blue'], 'FORMAT MIX': ['形式分析', 'teal'],
  'CREATOR EFFICIENCY': ['达人效率', 'purple'], 'GEOGRAPHY': ['地域分布', 'green'],
  'CONTENT RANKING': ['内容排行', 'blue'], 'MONTHLY SEARCH': ['竞品月报', 'purple'],
  'BRAND LANDSCAPE': ['竞争格局', 'blue'], 'SENTIMENT COMPOSITION': ['口碑结构', 'green'],
  'VOICE TREND': ['动态走势', 'blue'], 'TOPIC TAXONOMY': ['话题分析', 'teal'],
  'VOICE OF CUSTOMER': ['消费者洞察', 'purple'], 'ACTION SLA': ['行动闭环', 'amber'],
  'CROSS BRAND COMPARISON': ['品牌对比', 'blue'], 'STRATEGY MAP': ['策略洞察', 'purple'],
  'PROJECT SAMPLE': ['项目样本', 'blue'], 'SEARCH TREND': ['搜索趋势', 'teal'],
  'PROJECT TOTALS': ['目标进度', 'purple'], 'PROJECT PROFILE': ['项目资料', 'blue'],
  'ACCEPTANCE': ['验收标准', 'green'], 'BRAND SCOPE': ['品牌词库', 'teal'],
  'SUPPLEMENTAL REVIEW': ['审查规则', 'amber'], 'ACTION LOGIC': ['处置规则', 'amber'],
  'CUSTOM REVIEW RULES': ['自定义规则', 'purple'], 'PIPELINE CRUD': ['主线配置', 'blue'],
  'EXECUTION TARGET': ['执行目标', 'green'], 'COMMENT INGESTION': ['评论采集', 'blue'],
  'MONITORING LIST': ['采集监测', 'teal'], 'ACTION WORKBENCH': ['处置工作台', 'amber'],
  'PIPELINE DELIVERY': ['主线交付', 'green'], 'ACCEPTANCE DETAIL': ['验收明细', 'blue'],
  'DATA INTEGRITY': ['数据质量', 'teal'], 'NOTE PERFORMANCE': ['笔记表现', 'blue'],
  'INGESTION WORKSPACE': ['内容入库', 'blue'], 'NOTE REGISTRY': ['笔记台账', 'teal'],
  'COMMENT FETCH': ['评论抓取', 'blue'], 'NOTE DISCOVERY': ['内容发现', 'purple'],
  'OWNED NOTES': ['自有笔记', 'green'], 'NOTE ASSETS': ['笔记资产', 'blue'],
  'OWNED × ORGANIC': ['发布反馈', 'teal'], 'RECENT PUBLICATIONS': ['近期发布', 'blue'],
  'PUBLISHING PACING': ['发布节奏', 'blue'], 'RELEASE INVENTORY': ['发布清单', 'teal'],
  'COVERAGE FEEDBACK': ['反馈覆盖', 'purple'], 'RISK TRIAGE': ['风险分级', 'rose'],
  'SUPPLIER QA ACTIONS': ['供应商核验', 'blue'], 'VISIBILITY RATE': ['外显情况', 'teal'],
  'PASSING INSIGHTS': ['验收分析', 'green'], 'SUPPLIER AUDIT DETAIL': ['核验明细', 'blue'],
  'REVIEW QUEUE': ['审查队列', 'amber'], 'PLATFORM SIGNAL': ['高热灵感', 'blue'],
  'CURATED IDEA': ['灵感收录', 'purple'], 'IDEA PIPELINE': ['选题流转', 'teal'],
  'WATCHLIST': ['观察清单', 'purple'], 'KEYWORD RADAR': ['关键词机会', 'blue'],
  'BREAKOUT NOTES': ['高热样本', 'amber'], 'AUTO SEED': ['候选笔记', 'green'],
  'SAMPLE OPPORTUNITIES': ['内容机会', 'purple'],
};
