CREATE TABLE IF NOT EXISTS `note_profiles` (
  `note_id` text PRIMARY KEY NOT NULL,
  `cover_url` text DEFAULT '' NOT NULL,
  `content` text DEFAULT '' NOT NULL,
  `category1` text DEFAULT '' NOT NULL,
  `category2` text DEFAULT '' NOT NULL,
  `cooperation` integer DEFAULT 0 NOT NULL,
  `promoted` integer DEFAULT 0 NOT NULL,
  `note_type` text DEFAULT '' NOT NULL,
  `note_price` real DEFAULT 0 NOT NULL,
  `exposure` integer DEFAULT 0 NOT NULL,
  `read_count` integer DEFAULT 0 NOT NULL,
  `interaction_count` integer DEFAULT 0 NOT NULL,
  `like_count` integer DEFAULT 0 NOT NULL,
  `favorite_count` integer DEFAULT 0 NOT NULL,
  `share_count` integer DEFAULT 0 NOT NULL,
  `fans_count` integer DEFAULT 0 NOT NULL,
  `creator_level` text DEFAULT '' NOT NULL,
  `picture_price` real DEFAULT 0 NOT NULL,
  `video_price` real DEFAULT 0 NOT NULL,
  `province` text DEFAULT '' NOT NULL,
  `city` text DEFAULT '' NOT NULL,
  `gender` text DEFAULT '' NOT NULL,
  `read_median` integer DEFAULT 0 NOT NULL,
  `interaction_median` integer DEFAULT 0 NOT NULL,
  `brand` text DEFAULT '' NOT NULL,
  `updated_at` text NOT NULL
);
CREATE INDEX IF NOT EXISTS `idx_note_profiles_brand` ON `note_profiles` (`brand`);
